### ISSUE TITLE
Errors in tacc_reactors_base template

### ISSUE THREAD

**Issue by ethho** [TACC-Cloud/cc-tapis-v2-actors#6]
- [x] `secrets.json`
        - @shwetagopaul92 I believe I saw this error for other templates in this repo, such as `default`
```bash
$ tapis actors init --template tacc_reactors_base
[Errno 2] No such file or directory: 'secrets.json'
$ echo '{}' > secrets.json
```
- [ ] `message.jsonschema`
```bash
$ tapis actors deploy
Building enho/new_actor:1.0.0
ADD failed: file not found in build context or excluded by .dockerignore: stat message.jsonschema: file does not exist
# solution
$ ln -s message_schemas/message.jsonschema message.jsonschema
```
- [ ] `description` and `docker_base_repo` in [`cookiecutter.json`](https://github.com/TACC-Cloud/cc-tapis-v2-actors/blob/main/tacc_reactors_base/cookiecutter.json)
    - Test `python-reactors` CI/CD using `act` and `make image`
    - Test `tapis actors init/deploy` workflow again

**Comment by shwetagopaul92** [comment]
@eho-tacc For the `secrets.json` error message, we are providing the file as ` secrets.jsonsample` ; the user would have to rename it to `secrets.json` and it should work. 
I will document this so the user knows they should be renaming the file before running `tapis actors deploy`.

**Comment by ethho** [comment]
@shwetagopaul92 okay. Would it be bad practice to alternatively include an empty (`{}`) secrets.json in my template?

**Answer to my own question**: yes, it would be bad practice, because `secrets.json` should be in the `.gitignore`

**Comment by shwetagopaul92** [comment]
yes the secrets.json goes into .gitignore
